# Generated by Django 4.2.13 on 2026-06-13 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('slack_webhook_url', models.URLField(blank=True, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_on_critical', models.BooleanField(default=True)),
                ('alert_on_high', models.BooleanField(default=True)),
                ('alert_on_medium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
