# Generated by Django 4.2.13 on 2026-04-12 08:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(db_index=True, max_length=42)),
                ('network', models.CharField(choices=[('mainnet', 'Ethereum Mainnet'), ('polygon', 'Polygon'), ('bsc', 'Binance Smart Chain'), ('arbitrum', 'Arbitrum'), ('optimism', 'Optimism')], default='mainnet', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching Source'), ('analyzing', 'Analyzing'), ('ai_review', 'AI Review'), ('reporting', 'Generating Report'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('status_message', models.TextField(blank=True)),
                ('contract_name', models.CharField(blank=True, max_length=255)),
                ('compiler_version', models.CharField(blank=True, max_length=50)),
                ('source_code', models.TextField(blank=True)),
                ('abi', models.JSONField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('is_honeypot', models.BooleanField(blank=True, null=True)),
                ('slither_output', models.JSONField(blank=True, null=True)),
                ('mythril_output', models.JSONField(blank=True, null=True)),
                ('tenderly_output', models.JSONField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swc_id', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], max_length=20)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('line_numbers', models.CharField(blank=True, max_length=100)),
                ('code_snippet', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('tool', models.CharField(blank=True, max_length=50)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.scanjob')),
            ],
        ),
    ]
