# Generated by Django 4.2.13 on 2026-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='implementation_address',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='is_proxy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='proxy_address',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='proxy_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='source_files',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
