# Generated by Django 4.2.13 on 2026-06-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_proxy_multifile_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='analysis_mode',
            field=models.CharField(choices=[('source', 'Solidity Source'), ('bytecode', 'Bytecode (unverified)'), ('abi_only', 'ABI Only')], default='source', max_length=20),
        ),
    ]
