# Generated by Django 4.2.13 on 2026-06-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_analysis_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('detector', models.CharField(blank=True, max_length=100)),
                ('impact', models.CharField(blank=True, max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('line_numbers', models.CharField(blank=True, max_length=100)),
                ('code_snippet', models.TextField(blank=True)),
                ('estimated_gas_saving', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_issues', to='scanner.scanjob')),
            ],
        ),
    ]
