# Generated by Django 4.2.13 on 2026-06-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_gas_optimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='poc_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='poc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
