# Generated by Django 4.2.13 on 2026-06-13 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanner', '0005_poc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WatchedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('network', models.CharField(choices=[('mainnet', 'Ethereum Mainnet'), ('polygon', 'Polygon'), ('bsc', 'Binance Smart Chain'), ('arbitrum', 'Arbitrum'), ('optimism', 'Optimism')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('last_bytecode_hash', models.CharField(blank=True, max_length=66)),
                ('alert_on_new_vuln', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'address', 'network')},
            },
        ),
    ]
