# Generated by Django 4.2.13 on 2026-06-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_scanjob_user_watchedcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedcontract',
            name='rescan_frequency_days',
            field=models.IntegerField(default=0, help_text='0 means disabled. Otherwise, rescan every X days.'),
        ),
    ]
