# Generated by Django 4.2.13 on 2026-06-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_watchedcontract_rescan_frequency_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='public_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='share_label',
            field=models.CharField(blank=True, help_text='Custom branding label for the public report', max_length=100),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Ethereum Mainnet'), ('polygon', 'Polygon'), ('bsc', 'Binance Smart Chain'), ('arbitrum', 'Arbitrum'), ('optimism', 'Optimism'), ('solana', 'Solana'), ('aptos', 'Aptos'), ('sui', 'Sui'), ('ton', 'TON')], default='mainnet', max_length=20),
        ),
        migrations.AlterField(
            model_name='watchedcontract',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Ethereum Mainnet'), ('polygon', 'Polygon'), ('bsc', 'Binance Smart Chain'), ('arbitrum', 'Arbitrum'), ('optimism', 'Optimism'), ('solana', 'Solana'), ('aptos', 'Aptos'), ('sui', 'Sui'), ('ton', 'TON')], max_length=20),
        ),
    ]
