# Generated by Django 4.2.13 on 2026-06-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_scanjob_is_public_scanjob_public_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='call_graph_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
